---
title: "Fertilizer price model"
author: "Sebastian Palmas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
```

# Packages
```{r, message=FALSE}
library(terra)
library(tidyverse)
```

## Cities
```{r}
tza_alt <- rast("../data/CGIAR-SRTM/srtm_TZA.tif")
cities <- vect("F:/Work/Tanzania/ne_10m_populated_places_TZA.shp") %>% project(crs=crs(tza_alt))

#getting the projected coordinates and the populatoin
cities <- cbind(x=geom(cities)$x, y=geom(cities)$y, POP_MAX=cities$POP_MAX) %>% as.data.frame()

#keep only large cities
cities <- cities %>% dplyr::filter(POP_MAX>=50000)

#convert to spatial points needed in gdistance
cities <- sp::SpatialPoints(cbind(cities$x, cities$y))

```


## Access to cities of 50k or more
```{r}
acc50k <- rast("../results/tif/access/accCost50k.tif")
plot(acc50k, main="Access to large cities")
points(cities)

```
```{r}
hist(values(acc50k))
```

##Correcting factor
Logit transformation
```{r}
logistic <- function(x){
  #z <- 0 #to test
  L <- 2  #maximum value of curve #in this case, values above 1
  k <- .03   #logistic growth steepness of the curve
  x0 <- 180   #sigmoid midpoint
  #transformation
  z <- L/(1+exp(-k*(x-x0))) 
  z <- z+1   #to convert to multiplier 
  return(z)
}


#creating a plot and exporting to a file to use in figure

x <- seq(0,400, 10)
y <- logistic(x)
data_trans <- cbind(x,y) %>% as.data.frame()


g <- ggplot(data = data_trans, aes(x=x, y=y)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Access time to city 50k (min)",y="Price multiplier")
g


ggsave(filename = paste0('D:/OneDrive - CGIAR/Ex-Ante/Manuscript Ex-Ante/figures/FigX_fertilizer_priceA.tif'),
      plot = g,
      width = 90, height = 90, units = 'mm',
      device = 'tiff', dpi = 300)


```

## Correction
```{r}
#constant price
N_price_average <- 0.95   #USD/kg
N_price <- N_price_average*logistic(acc50k)
names(N_price) <- "N_price"
writeRaster(N_price, filename="../data/prices/TZA_N_price.tif", overwrite=TRUE)
plot(N_price, main="N price (USD/kg)")
```

Some summary stats for the paper
```{r}
N_price <- rast("../data/prices/TZA_N_price.tif")

print("larger then >2.5")
sum(values(N_price)>2.5, na.rm=TRUE)/sum(values(N_price)>0, na.rm=TRUE)

print("lower than < 1.5")
sum(values(N_price)<1.5, na.rm=TRUE)/sum(values(N_price)>0, na.rm=TRUE)

summary(values(N_price))
```

